version: 2
updates:

  - package-ecosystem: "nuget"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 100
    schedule:
      interval: "daily"
      
    ignore:
      - dependency-name: "Microsoft.NET.ILLink.Analyzers"
        versions: [ "*" ]
      - dependency-name: "Microsoft.DotNet.ILCompiler"
        versions: [ "*" ]
