name: Nuke CICD Pipeline
trigger:
  batch: true
  branches:
    include:
    - prerelease
    - main
  tags:
    include:
    - bump-*
pr:
  branches:
    include:
    - '**'
jobs:
- job: pre_setup
  displayName: Pre Setup
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-22.04
  steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0
  - script: chmod +x ./build.sh && ./build.sh PipelinePreSetup
    name: NUKE_RUN
    displayName: Run Nuke PipelinePreSetup
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
- job: NukeBuildHelpersTest1
  displayName: Test try 1
  pool:
    name: $(NUKE_PRE_SETUP_POOL_NAME)
    vmImage: $(NUKE_PRE_SETUP_POOL_VM_IMAGE)
  steps:
  - checkout: self
    persistCredentials: true
  - task: Cache@2
    displayName: Cache Run
    inputs:
      path: ./.nuke/cache
      key: $(NUKE_PRE_SETUP_CACHE_KEY)
      restoreKeys: |-
        $(NUKE_PRE_SETUP_CACHE_RESTORE_KEY)
        $(NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY)
  - script: echo "Test azure 1"
    name: test_azure_1
    displayName: Custom azure step test 1
  - script: $(NUKE_PRE_SETUP_RUN_SCRIPT) PipelineTest --args "NukeBuildHelpersTest1"
    name: NUKE_RUN
    displayName: Run Nuke PipelineTest
  - script: echo "Test azure 2"
    name: test_azure_2
    displayName: Custom azure step test 2
  dependsOn:
  - pre_setup
  condition: and(succeeded(), eq(variables.NUKE_PRE_SETUP_CONDITION, 'true'))
  variables:
    NUKE_PRE_SETUP: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP'] ]
    NUKE_PRE_SETUP_CONDITION: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest1_CONDITION'] ]
    NUKE_PRE_SETUP_POOL_NAME: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest1_POOL_NAME'] ]
    NUKE_PRE_SETUP_POOL_VM_IMAGE: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest1_POOL_VM_IMAGE'] ]
    NUKE_PRE_SETUP_RUN_SCRIPT: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest1_RUN_SCRIPT'] ]
    NUKE_PRE_SETUP_CACHE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest1_CACHE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest1_CACHE_RESTORE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest1_CACHE_MAIN_RESTORE_KEY'] ]
- job: NukeBuildHelpersTest2
  displayName: Test try 2
  pool:
    name: $(NUKE_PRE_SETUP_POOL_NAME)
    vmImage: $(NUKE_PRE_SETUP_POOL_VM_IMAGE)
  steps:
  - checkout: self
    persistCredentials: true
  - task: Cache@2
    displayName: Cache Run
    inputs:
      path: ./.nuke/cache
      key: $(NUKE_PRE_SETUP_CACHE_KEY)
      restoreKeys: |-
        $(NUKE_PRE_SETUP_CACHE_RESTORE_KEY)
        $(NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY)
  - script: $(NUKE_PRE_SETUP_RUN_SCRIPT) PipelineTest --args "NukeBuildHelpersTest2"
    name: NUKE_RUN
    displayName: Run Nuke PipelineTest
  dependsOn:
  - pre_setup
  condition: and(succeeded(), eq(variables.NUKE_PRE_SETUP_CONDITION, 'true'))
  variables:
    NUKE_PRE_SETUP: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP'] ]
    NUKE_PRE_SETUP_CONDITION: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest2_CONDITION'] ]
    NUKE_PRE_SETUP_POOL_NAME: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest2_POOL_NAME'] ]
    NUKE_PRE_SETUP_POOL_VM_IMAGE: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest2_POOL_VM_IMAGE'] ]
    NUKE_PRE_SETUP_RUN_SCRIPT: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest2_RUN_SCRIPT'] ]
    NUKE_PRE_SETUP_CACHE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest2_CACHE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest2_CACHE_RESTORE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersTest2_CACHE_MAIN_RESTORE_KEY'] ]
- job: NukeBuildHelpersBuild1
  displayName: Build main
  pool:
    name: $(NUKE_PRE_SETUP_POOL_NAME)
    vmImage: $(NUKE_PRE_SETUP_POOL_VM_IMAGE)
  steps:
  - checkout: self
    persistCredentials: true
  - task: Cache@2
    displayName: Cache Run
    inputs:
      path: ./.nuke/cache
      key: $(NUKE_PRE_SETUP_CACHE_KEY)
      restoreKeys: |-
        $(NUKE_PRE_SETUP_CACHE_RESTORE_KEY)
        $(NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY)
  - script: $(NUKE_PRE_SETUP_RUN_SCRIPT) PipelineBuild --args "NukeBuildHelpersBuild1"
    name: NUKE_RUN
    displayName: Run Nuke PipelineBuild
  - task: PublishPipelineArtifact@1
    displayName: Upload Artifacts
    inputs:
      artifact: nuke_build_helpers___NukeBuildHelpersBuild1
      targetPath: ./.nuke/output
      continueOnError: true
  dependsOn:
  - pre_setup
  - NukeBuildHelpersTest1
  - NukeBuildHelpersTest2
  condition: and(succeeded(), eq(variables.NUKE_PRE_SETUP_CONDITION, 'true'))
  variables:
    NUKE_PRE_SETUP: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP'] ]
    NUKE_PRE_SETUP_CONDITION: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild1_CONDITION'] ]
    NUKE_PRE_SETUP_POOL_NAME: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild1_POOL_NAME'] ]
    NUKE_PRE_SETUP_POOL_VM_IMAGE: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild1_POOL_VM_IMAGE'] ]
    NUKE_PRE_SETUP_RUN_SCRIPT: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild1_RUN_SCRIPT'] ]
    NUKE_PRE_SETUP_CACHE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild1_CACHE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild1_CACHE_RESTORE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild1_CACHE_MAIN_RESTORE_KEY'] ]
- job: NukeBuildHelpersBuild2
  displayName: Build try
  pool:
    name: $(NUKE_PRE_SETUP_POOL_NAME)
    vmImage: $(NUKE_PRE_SETUP_POOL_VM_IMAGE)
  steps:
  - checkout: self
    persistCredentials: true
  - task: Cache@2
    displayName: Cache Run
    inputs:
      path: ./.nuke/cache
      key: $(NUKE_PRE_SETUP_CACHE_KEY)
      restoreKeys: |-
        $(NUKE_PRE_SETUP_CACHE_RESTORE_KEY)
        $(NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY)
  - script: $(NUKE_PRE_SETUP_RUN_SCRIPT) PipelineBuild --args "NukeBuildHelpersBuild2"
    name: NUKE_RUN
    displayName: Run Nuke PipelineBuild
  - task: PublishPipelineArtifact@1
    displayName: Upload Artifacts
    inputs:
      artifact: nuke_build_helpers___NukeBuildHelpersBuild2
      targetPath: ./.nuke/output
      continueOnError: true
  dependsOn:
  - pre_setup
  - NukeBuildHelpersTest1
  - NukeBuildHelpersTest2
  condition: and(succeeded(), eq(variables.NUKE_PRE_SETUP_CONDITION, 'true'))
  variables:
    NUKE_PRE_SETUP: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP'] ]
    NUKE_PRE_SETUP_CONDITION: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild2_CONDITION'] ]
    NUKE_PRE_SETUP_POOL_NAME: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild2_POOL_NAME'] ]
    NUKE_PRE_SETUP_POOL_VM_IMAGE: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild2_POOL_VM_IMAGE'] ]
    NUKE_PRE_SETUP_RUN_SCRIPT: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild2_RUN_SCRIPT'] ]
    NUKE_PRE_SETUP_CACHE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild2_CACHE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild2_CACHE_RESTORE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild2_CACHE_MAIN_RESTORE_KEY'] ]
- job: NukeBuildHelpersBuild3
  displayName: Build try 2
  pool:
    name: $(NUKE_PRE_SETUP_POOL_NAME)
    vmImage: $(NUKE_PRE_SETUP_POOL_VM_IMAGE)
  steps:
  - checkout: self
    persistCredentials: true
  - task: Cache@2
    displayName: Cache Run
    inputs:
      path: ./.nuke/cache
      key: $(NUKE_PRE_SETUP_CACHE_KEY)
      restoreKeys: |-
        $(NUKE_PRE_SETUP_CACHE_RESTORE_KEY)
        $(NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY)
  - script: $(NUKE_PRE_SETUP_RUN_SCRIPT) PipelineBuild --args "NukeBuildHelpersBuild3"
    name: NUKE_RUN
    displayName: Run Nuke PipelineBuild
  - task: PublishPipelineArtifact@1
    displayName: Upload Artifacts
    inputs:
      artifact: nuke_build_helpers2___NukeBuildHelpersBuild3
      targetPath: ./.nuke/output
      continueOnError: true
  dependsOn:
  - pre_setup
  - NukeBuildHelpersTest1
  - NukeBuildHelpersTest2
  condition: and(succeeded(), eq(variables.NUKE_PRE_SETUP_CONDITION, 'true'))
  variables:
    NUKE_PRE_SETUP: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP'] ]
    NUKE_PRE_SETUP_CONDITION: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild3_CONDITION'] ]
    NUKE_PRE_SETUP_POOL_NAME: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild3_POOL_NAME'] ]
    NUKE_PRE_SETUP_POOL_VM_IMAGE: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild3_POOL_VM_IMAGE'] ]
    NUKE_PRE_SETUP_RUN_SCRIPT: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild3_RUN_SCRIPT'] ]
    NUKE_PRE_SETUP_CACHE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild3_CACHE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild3_CACHE_RESTORE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersBuild3_CACHE_MAIN_RESTORE_KEY'] ]
- job: NukeBuildHelpersPublish
  displayName: Publish - nuke_build_helpers
  pool:
    name: $(NUKE_PRE_SETUP_POOL_NAME)
    vmImage: $(NUKE_PRE_SETUP_POOL_VM_IMAGE)
  steps:
  - checkout: self
    persistCredentials: true
  - task: DownloadPipelineArtifact@2
    displayName: Download Artifacts
    inputs:
      itemPattern: nuke_build_helpers___*/**
      path: ./.nuke/temp/artifacts
      continueOnError: true
  - task: Cache@2
    displayName: Cache Run
    inputs:
      path: ./.nuke/cache
      key: $(NUKE_PRE_SETUP_CACHE_KEY)
      restoreKeys: |-
        $(NUKE_PRE_SETUP_CACHE_RESTORE_KEY)
        $(NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY)
  - script: $(NUKE_PRE_SETUP_RUN_SCRIPT) PipelinePublish --args "NukeBuildHelpersPublish"
    name: NUKE_RUN
    displayName: Run Nuke PipelinePublish
  dependsOn:
  - pre_setup
  - NukeBuildHelpersBuild1
  - NukeBuildHelpersBuild2
  - NukeBuildHelpersBuild3
  condition: and(succeeded(), eq(variables.NUKE_PRE_SETUP_CONDITION, 'true'))
  variables:
    NUKE_PRE_SETUP: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP'] ]
    NUKE_PRE_SETUP_CONDITION: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersPublish_CONDITION'] ]
    NUKE_PRE_SETUP_POOL_NAME: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersPublish_POOL_NAME'] ]
    NUKE_PRE_SETUP_POOL_VM_IMAGE: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersPublish_POOL_VM_IMAGE'] ]
    NUKE_PRE_SETUP_RUN_SCRIPT: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersPublish_RUN_SCRIPT'] ]
    NUKE_PRE_SETUP_CACHE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersPublish_CACHE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersPublish_CACHE_RESTORE_KEY'] ]
    NUKE_PRE_SETUP_CACHE_MAIN_RESTORE_KEY: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP_NukeBuildHelpersPublish_CACHE_MAIN_RESTORE_KEY'] ]
- job: post_setup
  displayName: Post Setup
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-22.04
  steps:
  - checkout: self
    persistCredentials: true
  - task: DownloadPipelineArtifact@2
    displayName: Download artifacts
    inputs:
      path: ./.nuke/temp/artifacts
      patterns: '**'
      continueOnError: true
  - script: chmod +x ./build.sh && ./build.sh PipelinePostSetup
    displayName: Run Nuke PipelinePostSetup
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
  dependsOn:
  - pre_setup
  - NukeBuildHelpersTest1
  - NukeBuildHelpersTest2
  - NukeBuildHelpersBuild1
  - NukeBuildHelpersBuild2
  - NukeBuildHelpersBuild3
  - NukeBuildHelpersPublish
  condition: always()
  variables:
    NUKE_PRE_SETUP: $[ dependencies.pre_setup.outputs['NUKE_RUN.NUKE_PRE_SETUP'] ]
    NUKE_RUN_RESULT_AZURE_NukeBuildHelpersTest1: $[ dependencies.NukeBuildHelpersTest1.result ]
    NUKE_RUN_RESULT_AZURE_NukeBuildHelpersTest2: $[ dependencies.NukeBuildHelpersTest2.result ]
    NUKE_RUN_RESULT_AZURE_NukeBuildHelpersBuild1: $[ dependencies.NukeBuildHelpersBuild1.result ]
    NUKE_RUN_RESULT_AZURE_NukeBuildHelpersBuild2: $[ dependencies.NukeBuildHelpersBuild2.result ]
    NUKE_RUN_RESULT_AZURE_NukeBuildHelpersBuild3: $[ dependencies.NukeBuildHelpersBuild3.result ]
    NUKE_RUN_RESULT_AZURE_NukeBuildHelpersPublish: $[ dependencies.NukeBuildHelpersPublish.result ]
