name: Nuke CICD Pipeline
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '**'
jobs:
- job: pre_setup
  displayName: Pre Setup
  pool:
    vmImage: ubuntu-22.04
  steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0
  - task: Cache@2
    inputs:
      path: $(NUGET_PACKAGES)
      key: '"ubuntu-22.04" | "nuget" | ./build/packages.lock.json'
      restore-keys: '"ubuntu-22.04" | "nuget"'
  - script: chmod +x ./build.sh && ./build.sh PipelinePreSetup --args "azure"
    name: setup
    displayName: Run Nuke PipelinePreSetup
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
