name: Nuke CICD Pipeline
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '**'
jobs:
- job: pre_setup
  displayName: Pre Setup
  pool:
    vmImage: ubuntu-22.04
  steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0
  - task: Cache@2
    inputs:
      path: ~/.nuget/packages
      key: '"ubuntu-22.04-nuget-"'
      restore-keys: '"ubuntu-22.04-nuget-"'
  - script: chmod +x ./build.sh && ./build.sh PipelinePreSetup --args "github"
    name: setup
    displayName: Run Nuke PipelinePreSetup
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
