name: Nuke CICD Pipeline
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '**'
jobs:
- job: pre_setup
  displayName: Pre Setup
  pool:
    vmImage: ubuntu-22.04
  steps:
  - checkout: self
    persistCredentials: true
    fetchDepth: 0
