name: Dependabot Pull Request Bump

on:
  push:
    branches:
    - main
    tags-ignore:
    - bump-*

concurrency: "dependabot-auto-bump"

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - name: Start nuke bump
        run: chmod +x ./build.sh && ./build.sh BumpAndForget --args "nuke_build_helpers=patch"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}