name: Dependabot Pull Request Bump

on:
  push:
    branches:
    - main
    tags-ignore:
    - bump-*

concurrency: "dependabot-auto-bump"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.commits[0].author.username == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - name: Start nuke bump
        run: chmod +x ./build.sh && ./build.sh BumpAndForget --args "nuke_build_helpers=patch"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  dependabot1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}