name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - main
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pre_setup:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup --args "github"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
  NugetBuildHelpersTest1:
    name: Test - ${{ env.nuke_entry_name }}
    runs-on: ${{ env.nuke_runs_on }}
    steps:
    - uses: actions/checkout@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
    - name: Cache Test
      uses: actions/cache@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
      with:
        path: ./.nuke/cache
        key: test-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-${{ env.nuke_run_identifier }}"
        restore-keys: |-
          test-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-
          test-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-main-
    - id: ${{ env.nuke_entry_ids_to_run }}
      name: Run Nuke PipelineTest
      run: ${{ env.nuke_run_script }} PipelineTest
      if: ${{ env.nuke_entry_id != 'skip' }}
    needs:
    - pre_setup
    if: success()
    env:
      NUKE_PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.NUKE_PRE_SETUP_OUTPUT }}
  NugetBuildHelpersTest2:
    name: Test - ${{ env.nuke_entry_name }}
    runs-on: ${{ env.nuke_runs_on }}
    steps:
    - uses: actions/checkout@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
    - name: Cache Test
      uses: actions/cache@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
      with:
        path: ./.nuke/cache
        key: test-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-${{ env.nuke_run_identifier }}"
        restore-keys: |-
          test-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-
          test-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-main-
    - id: ${{ env.nuke_entry_ids_to_run }}
      name: Run Nuke PipelineTest
      run: ${{ env.nuke_run_script }} PipelineTest
      if: ${{ env.nuke_entry_id != 'skip' }}
    needs:
    - pre_setup
    if: success()
    env:
      NUKE_PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.NUKE_PRE_SETUP_OUTPUT }}
  NugetBuildHelpersBuild:
    name: Build - ${{ env.nuke_entry_name }}
    runs-on: ${{ env.nuke_runs_on }}
    steps:
    - uses: actions/checkout@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
    - name: Cache Build
      uses: actions/cache@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
      with:
        path: ./.nuke/cache
        key: build-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-${{ env.nuke_run_identifier }}"
        restore-keys: |-
          build-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-
          build-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-main-
    - id: ${{ env.nuke_entry_ids_to_run }}
      name: Run Nuke PipelineBuild
      run: ${{ env.nuke_run_script }} PipelineBuild
      if: ${{ env.nuke_entry_id != 'skip' }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
      with:
        name: ${{ env.nuke_entry_id }}
        path: ./.nuke/output/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - pre_setup
    - NugetBuildHelpersTest1
    - NugetBuildHelpersTest2
    if: success()
    env:
      NUKE_PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.NUKE_PRE_SETUP_OUTPUT }}
  NugetBuildHelpersPublish:
    name: Publish - ${{ env.nuke_entry_name }}
    runs-on: ${{ env.nuke_runs_on }}
    steps:
    - uses: actions/checkout@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
    - name: Download artifacts
      uses: actions/download-artifact@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
      with:
        path: ./.nuke/output
        pattern: ${{ env.nuke_entry_id }}
        merge-multiple: true
    - name: Cache Publish
      uses: actions/cache@v4
      if: ${{ env.nuke_entry_id != 'skip' }}
      with:
        path: ./.nuke/cache
        key: publish-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-${{ env.nuke_run_identifier }}"
        restore-keys: |-
          publish-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-${{ env.nuke_run_classification }}-
          publish-${{ env.nuke_runner_name }}-${{ env.nuke_entry_id }}-${{ env.nuke_cache_invalidator }}-${{ env.nuke_environment }}-main-
    - id: ${{ env.nuke_entry_ids_to_run }}
      name: Run Nuke PipelinePublish
      run: ${{ env.nuke_run_script }} PipelinePublish
      if: ${{ env.nuke_entry_id != 'skip' }}
    needs:
    - pre_setup
    - NugetBuildHelpersBuild
    if: success()
    env:
      NUKE_PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.NUKE_PRE_SETUP_OUTPUT }}
  post_setup:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - id: NUKE_PUBLISH_SUCCESS
      name: Resolve NUKE_PUBLISH_SUCCESS
      run: echo "NUKE_PUBLISH_SUCCESS=${NUKE_PUBLISH_SUCCESS_GITHUB/success/ok}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/output
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
      env:
        NUKE_PUBLISH_SUCCESS: ${{ steps.NUKE_PUBLISH_SUCCESS.outputs.NUKE_PUBLISH_SUCCESS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
    - pre_setup
    - NugetBuildHelpersPublish
    if: success() || failure() || always()
    env:
      NUKE_PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.NUKE_PRE_SETUP_OUTPUT }}
      NUKE_PUBLISH_SUCCESS_GITHUB: ${{ needs.publish.result }}
env:
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
