name: Nuke CICD Pipeline
on:
  push:
    branches:
    - master
    - alpha
concurrency:
  group: nuke-cicd
jobs:
  pre_setup:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
  test:
    name: Test - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v3
    needs:
    - setup
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers_test
          name: NugetBuildHelpersTest
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers_test2
          name: NugetBuildHelpersTest2
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers_test3
          name: NugetBuildHelpersTest3
          runs_on: ubuntu-22.04
  post_setup:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - setup
