name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - main
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CONDITION }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_RUNS_ON }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_RUN_SCRIPT }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CONDITION }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_RUNS_ON }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_RUN_SCRIPT }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CONDITION }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_RUNS_ON }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_RUN_SCRIPT }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CONDITION }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_RUNS_ON }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_RUN_SCRIPT }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CONDITION }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_RUNS_ON }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_RUN_SCRIPT }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CONDITION }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_RUNS_ON }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_RUN_SCRIPT }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
  NUKEBUILDHELPERSTEST1:
    name: Test try 1
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CACHE_MAIN_RESTORE_KEY }}
    - id: test_github_1
      name: Custom github step test 1
      run: echo "Test github 1"
    - id: NUKE_RUN
      name: Run Nuke PipelineTest
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_RUN_SCRIPT }} PipelineTest --args "NukeBuildHelpersTest1"
    - id: test_github_2
      name: Custom github step test 2
      run: echo "Test github 2"
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST1_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  NUKEBUILDHELPERSTEST2:
    name: Test try 2
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineTest
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_RUN_SCRIPT }} PipelineTest --args "NukeBuildHelpersTest2"
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST2_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  NUKEBUILDHELPERSTEST3:
    name: Test try 3
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineTest
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_RUN_SCRIPT }} PipelineTest --args "NukeBuildHelpersTest3"
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSTEST3_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  NUKEBUILDHELPERSBUILD1:
    name: Build main
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineBuild
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_RUN_SCRIPT }} PipelineBuild --args "NukeBuildHelpersBuild1"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuke_build_helpers___NUKEBUILDHELPERSBUILD1
        path: ./.nuke/output/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - NUKEBUILDHELPERSTEST1
    - NUKEBUILDHELPERSTEST2
    - NUKEBUILDHELPERSTEST3
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD1_CONDITION == 'true' && needs.NUKEBUILDHELPERSTEST1.result == 'success' && needs.NUKEBUILDHELPERSTEST2.result == 'success' && needs.NUKEBUILDHELPERSTEST3.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  NUKEBUILDHELPERSBUILD2:
    name: Build try
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineBuild
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_RUN_SCRIPT }} PipelineBuild --args "NukeBuildHelpersBuild2"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuke_build_helpers___NUKEBUILDHELPERSBUILD2
        path: ./.nuke/output/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - NUKEBUILDHELPERSTEST1
    - NUKEBUILDHELPERSTEST2
    - NUKEBUILDHELPERSTEST3
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD2_CONDITION == 'true' && needs.NUKEBUILDHELPERSTEST1.result == 'success' && needs.NUKEBUILDHELPERSTEST2.result == 'success' && needs.NUKEBUILDHELPERSTEST3.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  NUKEBUILDHELPERSBUILD3:
    name: Build try 2
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineBuild
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_RUN_SCRIPT }} PipelineBuild --args "NukeBuildHelpersBuild3"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuke_build_helpers2___NUKEBUILDHELPERSBUILD3
        path: ./.nuke/output/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - NUKEBUILDHELPERSTEST1
    - NUKEBUILDHELPERSTEST2
    - NUKEBUILDHELPERSTEST3
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSBUILD3_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  NUKEBUILDHELPERSPUBLISH:
    name: Publish - nuke_build_helpers (NukeBuildHelpersPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
        pattern: nuke_build_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelinePublish
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_RUN_SCRIPT }} PipelinePublish --args "NukeBuildHelpersPublish"
    needs:
    - PRE_SETUP
    - NUKEBUILDHELPERSBUILD1
    - NUKEBUILDHELPERSBUILD2
    - NUKEBUILDHELPERSBUILD3
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_NUKEBUILDHELPERSPUBLISH_CONDITION == 'true' && needs.NUKEBUILDHELPERSTEST1.result != 'failure' && needs.NUKEBUILDHELPERSTEST2.result != 'failure' && needs.NUKEBUILDHELPERSTEST3.result != 'failure' && needs.NUKEBUILDHELPERSBUILD1.result != 'failure' && needs.NUKEBUILDHELPERSBUILD2.result != 'failure'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
    - PRE_SETUP
    - NUKEBUILDHELPERSTEST1
    - NUKEBUILDHELPERSTEST2
    - NUKEBUILDHELPERSTEST3
    - NUKEBUILDHELPERSBUILD1
    - NUKEBUILDHELPERSBUILD2
    - NUKEBUILDHELPERSBUILD3
    - NUKEBUILDHELPERSPUBLISH
    if: success() || failure() || always()
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_NUKEBUILDHELPERSTEST1: ${{ needs.NUKEBUILDHELPERSTEST1.result }}
      NUKE_RUN_RESULT_GITHUB_NUKEBUILDHELPERSTEST2: ${{ needs.NUKEBUILDHELPERSTEST2.result }}
      NUKE_RUN_RESULT_GITHUB_NUKEBUILDHELPERSTEST3: ${{ needs.NUKEBUILDHELPERSTEST3.result }}
      NUKE_RUN_RESULT_GITHUB_NUKEBUILDHELPERSBUILD1: ${{ needs.NUKEBUILDHELPERSBUILD1.result }}
      NUKE_RUN_RESULT_GITHUB_NUKEBUILDHELPERSBUILD2: ${{ needs.NUKEBUILDHELPERSBUILD2.result }}
      NUKE_RUN_RESULT_GITHUB_NUKEBUILDHELPERSBUILD3: ${{ needs.NUKEBUILDHELPERSBUILD3.result }}
      NUKE_RUN_RESULT_GITHUB_NUKEBUILDHELPERSPUBLISH: ${{ needs.NUKEBUILDHELPERSPUBLISH.result }}
env:
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
