name: Nuke CICD Pipeline
on:
  push:
    branches:
    - master
    - alpha
concurrency:
  group: nuke-cicd
jobs:
  setup:
    name: Project Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
  test_nuget_build_helpers_test:
    name: Test - NugetBuildHelpersTest
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - setup
  test_nuget_build_helpers_test2:
    name: Test - NugetBuildHelpersTest2
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - setup
  test_nuget_build_helpers_test3:
    name: Test - NugetBuildHelpersTest3
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - setup
  build_nuget_build_helpers:
    name: Build - NugetBuildHelpers
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - test_nuget_build_helpers_test
    - test_nuget_build_helpers_test3
  build_nuget_build_helpers2:
    name: Build - NugetBuildHelpers2
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - test_nuget_build_helpers_test2
    - test_nuget_build_helpers_test3
  build_nuget_build_helpers3:
    name: Build - NugetBuildHelpers3
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs: []
  publish_nuget_build_helpers:
    name: Publish - NugetBuildHelpers
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
  publish_nuget_build_helpers2:
    name: Publish - NugetBuildHelpers2
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
  publish_nuget_build_helpers3:
    name: Publish - NugetBuildHelpers3
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
  cleanups:
    name: Cleanups
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
