name: Nuke CICD Pipeline
on:
  push:
    branches:
    - '*'
    tags:
    - '**'
  pull_request:
    branches:
    - fix/**
    - feat/**
    - hotfix/**
concurrency:
  group: nuke-cicd
jobs:
  pre_setup:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - id: setup
      name: Run Nuke
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup && echo "PRE_SETUP_OUTPUT=$(cat ./.nuke/temp/pre_setup_output.json)" >> $GITHUB_OUTPUT
    outputs:
      PRE_SETUP_OUTPUT: ${{ steps.setup.outputs.PRE_SETUP_OUTPUT }}
  test:
    name: Test - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Nuke Prepare
      run: ${{ matrix.build_script }} PipelinePrepare --args "${{ matrix.ids_to_run }}"
    - name: Run Nuke Test
      run: ${{ matrix.build_script }} PipelineTest --args "${{ matrix.ids_to_run }}"
    needs:
    - pre_setup
    env:
      PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.PRE_SETUP_OUTPUT }}
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers_test
          name: NugetBuildHelpersTest
          runs_on: windows-latest
          build_script: ./build.cmd
          ids_to_run: nuget_build_helpers;nuget_build_helpers_test
        - id: nuget_build_helpers_test2
          name: NugetBuildHelpersTest2
          runs_on: windows-2022
          build_script: ./build.cmd
          ids_to_run: nuget_build_helpers2;nuget_build_helpers_test2
        - id: nuget_build_helpers_test3
          name: NugetBuildHelpersTest3
          runs_on: ubuntu-22.04
          build_script: chmod +x ./build.sh && ./build.sh
          ids_to_run: nuget_build_helpers;nuget_build_helpers_test3
  build:
    name: Build - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Nuke Prepare
      run: ${{ matrix.build_script }} PipelinePrepare --args "${{ matrix.ids_to_run }}"
    - name: Run Nuke Build
      run: ${{ matrix.build_script }} PipelineBuild --args "${{ matrix.ids_to_run }}"
    needs:
    - pre_setup
    - test
    env:
      PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.PRE_SETUP_OUTPUT }}
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers
          name: NugetBuildHelpers
          runs_on: ubuntu-22.04
          build_script: chmod +x ./build.sh && ./build.sh
          ids_to_run: nuget_build_helpers
        - id: nuget_build_helpers2
          name: NugetBuildHelpers2
          runs_on: windows-2022
          build_script: ./build.cmd
          ids_to_run: nuget_build_helpers2
        - id: nuget_build_helpers3
          name: NugetBuildHelpers3
          runs_on: ubuntu-latest
          build_script: chmod +x ./build.sh && ./build.sh
          ids_to_run: nuget_build_helpers3
  publish:
    name: Publish - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Nuke Publish
      run: ${{ matrix.build_script }} PipelinePublish --args "${{ matrix.ids_to_run }}"
    needs:
    - pre_setup
    - test
    - build
    env:
      PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.PRE_SETUP_OUTPUT }}
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers
          name: NugetBuildHelpers
          runs_on: ubuntu-22.04
          build_script: chmod +x ./build.sh && ./build.sh
          ids_to_run: nuget_build_helpers
        - id: nuget_build_helpers2
          name: NugetBuildHelpers2
          runs_on: windows-2022
          build_script: ./build.cmd
          ids_to_run: nuget_build_helpers2
        - id: nuget_build_helpers3
          name: NugetBuildHelpers3
          runs_on: ubuntu-latest
          build_script: chmod +x ./build.sh && ./build.sh
          ids_to_run: nuget_build_helpers3
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    needs:
    - pre_setup
    - test
    - build
    env:
      PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.PRE_SETUP_OUTPUT }}
  post_setup:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    needs:
    - pre_setup
    - test
    - build
    - publish
    - release
    env:
      PRE_SETUP_OUTPUT: ${{ needs.pre_setup.outputs.PRE_SETUP_OUTPUT }}
