name: Nuke CICD Pipeline
on:
  push:
    branches:
    - master
    - alpha
concurrency:
  group: nuke-cicd
jobs:
  pre_setup:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
  test:
    name: Test - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v3
    needs:
    - pre_setup
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers_test
          name: NugetBuildHelpersTest
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers_test2
          name: NugetBuildHelpersTest2
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers_test3
          name: NugetBuildHelpersTest3
          runs_on: ubuntu-22.04
  build:
    name: Build - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v3
    needs:
    - pre_setup
    - test
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers
          name: NugetBuildHelpers
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers2
          name: NugetBuildHelpers2
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers3
          name: NugetBuildHelpers3
          runs_on: ubuntu-22.04
  publish:
    name: Publish - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v3
    needs:
    - pre_setup
    - test
    - build
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers
          name: NugetBuildHelpers
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers2
          name: NugetBuildHelpers2
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers3
          name: NugetBuildHelpers3
          runs_on: ubuntu-22.04
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - pre_setup
    - test
    - build
  post_setup:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    needs:
    - pre_setup
    - test
    - build
    - publish
    - release
