name: Nuke CICD Pipeline
on:
  push:
    branches:
    - master
    - alpha
concurrency:
  group: nuke-cicd
jobs:
  pre_setup:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
  test:
    name: Test - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Nuke
      run: ${{ matrix.build_script }} test
    needs:
    - pre_setup
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers_test
          name: NugetBuildHelpersTest
          runs_on: windows-latest
          build_script: ./build.cmd
        - id: nuget_build_helpers_test2
          name: NugetBuildHelpersTest2
          runs_on: windows-2022
          build_script: ./build.cmd
        - id: nuget_build_helpers_test3
          name: NugetBuildHelpersTest3
          runs_on: ubuntu-22.04
          build_script: chmod +x ./build.sh | ./build.sh
  build:
    name: Build - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v4
    - name: Run Nuke
      run: ./build pack
    needs:
    - pre_setup
    - test
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers
          name: NugetBuildHelpers
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers2
          name: NugetBuildHelpers2
          runs_on: windows-2022
        - id: nuget_build_helpers3
          name: NugetBuildHelpers3
          runs_on: ubuntu-latest
  publish:
    name: Publish - ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v4
    needs:
    - pre_setup
    - test
    - build
    strategy:
      matrix:
        include:
        - id: nuget_build_helpers
          name: NugetBuildHelpers
          runs_on: ubuntu-22.04
        - id: nuget_build_helpers2
          name: NugetBuildHelpers2
          runs_on: windows-2022
        - id: nuget_build_helpers3
          name: NugetBuildHelpers3
          runs_on: ubuntu-latest
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    needs:
    - pre_setup
    - test
    - build
  post_setup:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    needs:
    - pre_setup
    - test
    - build
    - publish
    - release
